# import keyword
# print(keyword.kwlist)

# str1 = "    123123123\n\t\r"
# print(str1.strip())
#
# str2 = "******123******"
# print(str2.strip("*"))
#
# str3 = "123321213231***123321132231"
# print(str3.strip("123"))
# print(str3.strip("132"))
# print(str3.strip("213"))
#
# str4 = "123321213231**123**123321132231"
# print(str4.strip("213"))
#
# str5 = "123321213231**123**123321132231"
# print(str3.strip("123456789"))
#
# list1 = [1, 1, 2]
# print(list1)
lst = ['                                                                ', ' ', '                             ', ' ',
       ' ', '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ', ' ',
       '      East West Bank   ', '     Global  Checking   ', ' ',
       '       Interest Rates                                                  ', ' ', '  ', '                    ',
       '                           Daily Balance       ', 'Interest Rate         ', 'Annual Percentage Yield  ', ' ',
       '$0.00   ', ' to  ', '$9,999.99             0.025% 0.03% ', ' ', '$10,000.00  ', ' to  ',
       '$24,999.99             0.025% 0.03% ', ' ', '$25,000.00  ', 'to  ', '$49,999.99             0.025% 0.03% ', ' ',
       '$50,000.00  ', 'to  ', '$99,999.99             0.025% 0.03% ', ' ', '$100,000.00   ', 'to  ',
       '$249,999.99             0.045% 0.05% ', ' ', '$250,000.00  ', 'to  ', '$499,999.99             0.045% 0.05% ',
       ' ', '$500,000.00  ', 'to  ', '$999,999.99             0.045% 0.05% ', ' ', '$1,000,000.00   ', 'to  ',
       '           and above             0.045% 0.05% ', ' ', ' ', '  Variable Rate Account   ',
       'Your interest rate is variable and may be changed  at any time, at our discretion and without ',
       'prior notice.  ', ' ', ' ', 'Interest Accrual /  ', 'Payment Frequency   ',
       'Interest begins to accrue on the day you make your deposit, and is credited to your account ',
       'on a monthly basis.  ', ' ', ' ', 'Interest Compounding / ', 'Computation   ',
       'Your interest is compounded daily on an actual/365 day basis.  We use the daily balance method, which applies a daily periodic rate to the principal in the account each day.  ',
       ' ', '         ', '       Terms and Conditions  ', ' ', ' ', 'Minimum Opening Balance   ', '$25,000  ', ' ',
       'Account must be funded within 60 days of  application approval with a  minimum opening ',
       'deposit of $25,000  or more .  Funding deposits received for an amount that is less than $25,000 ',
       'are, at the discretion of the Bank, subject to return . Accounts that are not funded within 60 ',
       'days  will be subject to automatic closure.  ', ' ',
       'Additionally, the Bank reserves  the right to automatically close  an account that at any time has ',
       'had a continuous $0 balance for 60 days,  that is overdrawn or otherwise not maintained in ',
       'good standing, or  for any reason in accordance with the terms of the Bank’s Deposit ',
       'Agreement .  Generally, accounts with an unresolved  overdraft condition will be closed within   ',
       '45 days  of the overdraft date, but  timing of the closure is solely at the discretion of the Bank. ',
       'For additional information please refer to Bank’s Deposit Agreement.  ', ' ',
       'Requests  to re -open an account  that h as been closed  by the Bank or customer are  subject to ',
       'Bank review and approval . If, at the Bank’s discretion, an account re -opening request is ',
       'honored , the minimum opening balance requirement will apply . The Bank is under no ',
       'obligation to honor a re -opening request, and not all accounts will qualify for re -opening.  Please ',
       'refer to the Bank’s  Deposit Agreement , provided at the time of account opening, for additional ',
       'information .  ', ' ', ' ', ' ', 'Account Opening Fee   ', '$300   ', ' ',
       'A one-time Account Opening Fee will be automatically deducted  from the account upon ',
       'receipt of a minimum opening deposit of $ 25,000 or more.   ', ' ',
       '\uf0a7 Depending on your initial funding amount, the  deduction of the Account Opening Fee ',
       'may result in your account balance falling below the minimum average balance required ',
       'to avoid a monthly account maintenance fee.   ', ' ',
       '(See “Account Opening Fee Refund  Qualification Requirements ” and “Minimum Average Balance Required ',
       'to Avoid the Monthly Maintenance Fee” section s for additional information.)  ', ' ', '\uf0a7  ', '  ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       '                                                                                                                                                                                                                                                                                                                     Global Checkin g 4-13-2024 I Page 1 of 4  ',
       ' ', '                                                                 ', '        ',
       '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ',
       '                                                                                                              Cont.       ',
       ' ', 'Monthly Maintenance Fee   ', '$25 ', ' ',
       'Charged per monthly statement cycle if the minimum average monthly balance maintained in ',
       'the account during the statement cycle does not meet the required minimum.  ', ' ',
       '\uf0a7 Please note, your Monthly Maintenance Fee assessment will be waived for the first two ',
       'monthly statement cycles after account opening.  For example, if you open your account ',
       'in January, your first Monthly Maintance Fee assessment will be for the month of Ma rch.    ', '   ',
       'Minimum Average Balance ', 'Required to Avoid the Monthly ',
       'Maintenance Fee      Your Monthly Maintenance Fee will be waived if you maintain a:  ', ' ',
       '1. $25,000 average balance in your account each monthly statement cycle  ',
       '                                         OR ',
       '2. $50,000  prior month -end combined average balance  in the qualifying consumer ',
       'deposit accounts you own at East West Bank  ', ' ', 'Account Opening Fee Refund  ',
       'Qualification R equirements   ',
       'During the first 12 months  (full or partial)  after the initial funding requirement is met, you will ',
       'have an opportunity to qualify for up to $300  in Account Opening Fee refunds .  ', ' ',
       '\uf0a7 For each month  during the qualification period where you have maintained a combined ',
       'month -end average balance of $100,000 or more  in the qualifying consumer deposit ',
       'accounts you own at East West Bank, you’ll receive a $100  Account Opening Fee refund . ', ' ',
       '\uf0a7 Upon qualification, your  $100 Account Opening Fee refund will be automatically  ',
       'credited to your Global Checking account  within 10 business days . ', ' ',
       'o Maximum refund amount:  $300, earned over 3 qualifying months  ', ' ',
       'Additionally, a t the sole discretion of the Bank, the initial Account Opening Fee may be ',
       'refunded  if, due to the Bank’s post -funding fraud risk assessment s, the account is closed by ',
       'the Bank within the first 30 calendar days after payment of the Account Opening Fee.  As ',
       'applicable , the Account Opening Fee refund amount will be credited to the account at the time ',
       'of closure.   ',
       '                                                                                                                                                                                ',
       'Additional Terms and Conditions                                                                                             ',
       '   ', ' ', 'Qualification Requirements   ',
       'Limited to individuals 18 years of age or older.  One account per customer.  ', ' ', ' ',
       'Subject to Bank Approval   ',
       'Account applications are subject to verification and approval. Submission of an application ',
       'does not guarantee that East West Bank will open an account for you.   ', ' ',
       'Additionally, we may conduct fraud risk assessments both at the time of application, and upon ',
       'receipt of your initial funding deposit, which may result in your initial funding deposit being ',
       'subject to certain access and usage limitations  until the fraud risk assessments are completed. ',
       'If you have questions regarding your initial funding deposit after account opening, you can contact us at (CN) +',
       '86.400. 080.5290  or (U.S.) + 1.833.468.8356.     ', ' ',
       'East West Bank reserves the right to close an account and return the initial funding deposit to the sender, without prior notice, based on the results of our risk assessment findings.   ',
       ' ', ' ', 'Account Title and  ', 'Contact Information   ',
       'By submitting an application you are requesting to open a Global  Checking account at East ',
       'West Bank, a United States financial institution.  If approved, a Global Checking  account will ',
       'be opened in your name, as sole owner.  Your contact e- mail address, mobile phone number, ',
       'primary residence address and alternate account mailing address will be defined based on the ',
       'information you agreed to share with us.  If an alternate ac count mailing address was not ',
       'provided, we will use your residence address as the mailing address for your account.  ', '          ',
       'Check Orders   ',
       'Your East West Bank account will NOT have checks automatically issued. If you would like to ',
       'order checks you may contact us at (CN) + 86.400. 080.5290 or (U.S.) + 1.833.468.8356.  ', ' ', ' ',
       'Check Imaging   ',
       'Check Imaging is a process of capturing, indexing, storing and retrieving electronic images of ',
       'checks.  Imaging systems replace the handling, distribution and storage of checks with ',
       'electronic images.  The images are retained by us for a period of seven years from the date of ', 'posting.  ',
       ' ',
       'By using your account you agree to this procedure and authorize us to destroy the original items and check.  You agree to allow any imaged document, or copy thereof, to serve as an ',
       'original item for any and all purposes, including charging your account or determining the ',
       'validity of any signatures or otherwise.  ', ' ', ' ', ' ',
       '                                                                                                                                                                                                                                                                                                                       Global Checking 4-13-2024 I Page 2 of 4                                                                  ',
       '         ', '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ',
       '                                                                                                              Cont.  ',
       '  ', ' ', 'Debit Card Issuance /  ', 'ATM Access  ', '  ',
       'A Debit Card will NOT be automatically issued.  If you would like to request a Debit Card you ',
       'may request a card in our M obile App or Online Banking service s, or contact us at (CN) ',
       '+86.400. 080.5290 or (U.S.) + 1.833.468.8356.  ', ' ',
       'If requested, your Debit Card will be issued in your name and mailed to the address associated ',
       'with your Global  Checking  account. For shipments to China, your Debit Card will be mailed to ',
       'the one- time shipping address you provided and verified at the time of request.  For cards ',
       'delivered to an international address, a shipping fee will apply.  Please refer to the East West ',
       'Bank Fee Schedule  for additional details.  ', ' ',
       'Your Global  Checking account will be linked as the primary account that can be accessed using ',
       'the Debit Card.  ', ' ', ' ', 'ATM Withdrawal Fees  ', '  ',
       'There is no charge for using an East West Bank ATM.    ', ' ',
       'Additionally, East West Bank will not charge you a fee when you use a non -East West Bank (3rd ',
       'party) ATM to access funds in your Global Checking  account.   ', ' ',
       'In some cases, the 3rd party operating the non -East West Bank ATM may request us to charge ',
       'a fee to your account.  If this does occur, East West Bank will refund any 3rd party ATM usage ',
       'fees deducted from your Global Checking  account each statement cycle, generally no later ',
       'than the business day following the day the transaction posted to your account.  (Note: This ',
       'waiver does not apply to any East West Bank NSF fees that are the result of your account being ',
       'overdrawn by an AT M transaction.)  ', ' ', ' ', 'Other Fees and Services  ', '  ',
       'Additional fees may apply.  Please refer to the East West Bank Fee Schedule , which has been ',
       'provided with this disclosure, for additional fee information.  ', ' ', 'Velo Gold  ', ' ', ' ',
       'Velo Gold Program  ', '  ',
       'Global Checking customers also have the opportunity to qualify for  our Velo Gold  program, ',
       'which offers enhanced features and benefits.  ', ' ', ' ', 'VELO Gold Benefits  ', '  ',
       'Velo Gold  Benefits include:  ', ' ', '\uf0fc WAIVER of Incoming Wire Fees  ', ' ',
       'We’ll waive East West Bank’s  Incoming Wire fee for your Global Checking account  ', ' ',
       '\uf0fc WAIVER of the International Shipping Fee for Debit Cards  ', ' ',
       'We’ll waive East West Bank’s  International Shipping Fee for Debit Cards  ', ' ',
       'Note:  International Shipping fee is applicable to select countries only  ', ' ',
       '\uf0fc Curated Articles and Resources  ', ' ',
       'Velo Gold  customers will have access to curated articles and resource information in the ',
       '“For You” section of our Mobile App and Online Banking services  ', ' ',
       'Additionally, Velo Gold  customers will have access to these other premium services:  ', ' ',
       '\uf0fc Dedicated Customer Support  ', ' ',
       'You’ll enjoy easy Mobile App and Online Banking access to our dedicated Help Center ',
       'phone line and chat support  ', ' ', '\uf0fc Relationship Manager  ', ' ',
       'A dedicated Relationship Manager, to support all your banking needs  ', ' ', ' ', 'Velo Gold Qualification  ',
       'Requirements  ', '  ', 'To qualify  for the Velo Gold  program , you must be:  ', ' ',
       '1. The primary owner of a Global Checking account; AND  ', ' ',
       '2. Maintain  a combined month -end average balance of $100,000 or more  in the qualifying ',
       'consumer deposit accounts you  own at East West Bank.  ', ' ',
       '\uf0a7 Upon meeting the combined month -end average balance requirement, both you ',
       'and your  Global Checking account  will be  automatically  ENROLLED  in the Velo Gold  ',
       'program  within 10 business days.  ', ' ',
       '                                                                                                                               ',
       ' ', ' ',
       '                                                                                                                                                             ',
       '                                                                                                                                                                                  Global Checking  4-13-2024  I Page 3 of 4                                                                 ',
       '         ', '                          ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ',
       '                                                                                                              Cont.  ',
       '  ', ' ', 'Velo Gold Qualification  ', 'Requirements (cont.)  ', ' ', '  ', ' ',
       'If, at any time,  the combined month -end average balances  in the qualifying consumer deposit ',
       'accounts you own at East West Bank fall below $100,000 for four (4) consecutive months , both ',
       'you and your  Global Checking account will be UNENROLLED from the Velo Gold  program  within ',
       '10 business days.  ', ' ',
       '\uf0a7 Customers and accounts that have been unenrolled from the Velo Gold program  will be ',
       'automatically RE -ENROLLED if they again meet  the Velo Gold  program  qualification ', 'requirements.  ', ' ',
       ' ', 'Additional Terms and ', 'Conditions  ', '  ',
       'Qualifying consumer deposit accounts for Maintenance Fee Waiver and Velo Gold program  ',
       'qualification purposes are determined by East West Bank. The balance from a qualifying ',
       'account will be allocated to a single account owner’s combined balance calculation only, and ',
       'the account owner   that will receive the allocation will be determined solely by East West Bank.  ',
       'Wealth Management accounts, Commercial accounts and other non -USD deposit account ',
       'products do not qualify.  ', ' ',
       'Customers that are currently enrolled in the  Velo Gold  program  generally will not qualify for ',
       'new enrollment in the Bank’s exclusiveBridgePlus or eliteBridgePlus programs.  ', ' ',
       'The Velo Gold  program benefits  are not exchangeable for other services, are  non-transferable ',
       'and have no cash  or rebate value.  Velo Gold  program  terms and benefits are subject  to change ',
       'or termination at the discretion of East West bank without notice.  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       '                                                                                                                                                             ',
       '                                                                                                                                                                                Global Checking  4-13-2024  I Page 4 of 4                                                              ',
       ' ', ' ', '                             ', ' ', '  ', ' ', ' ', 'Global  Checking  ',
       'DEPOSIT AGREEMENT ADDENDUM  ', 'Effective January 26, 202 3 ', ' ',
       'This Deposit Agreement Addendum  amends and supersedes, where applicable, the Bank’s Deposit Agreement  ',
       'dated 6/18/2015 and applies specifically to accounts opened using the East W est Bank  Mobile App or Online ',
       'Banking services.  ', ' ', '   ', '  ', '1. Holds for Uncollected Funds / Delayed Funds Availability  ',
       'Updated October 2 , 2023     ',
       '      The below revised information amends the “Ability to Withdrawal Funds”, “Longer Delays May Apply” and “Special Rules for ',
       'New Accounts”  information contained in the Holds for Uncollected Funds / Delayed Funds Availability  section of the Bank’s ',
       'Deposit Agreement . All other information contained in the Holds for Uncollected Funds / Delayed Funds Availability  section ',
       'of the Deposit Agreement  remains the same.  ', ' ',
       'Ability to Withdrawal Funds - Generally, our policy is to make funds from your deposits available to you on the first business ',
       'day after the day we receive your deposit, although specific account types, check types or deposit methods may be subject ',
       'to delayed funds availability. Electronic direct deposits will be available on the day we receive the deposit. Once they are ',
       'available, y ou can withdraw the funds in cash and we will use the funds to pay checks that you have written.  ',
       ' ',
       'In many cases we will make the funds from your deposited checks available to you sooner than we are able to collect the funds from the paying bank, and it is possible for a check or other item to be returned to us as unpaid days, weeks or months  ',
       'after we h ave made the funds available to you. Please remember that even after we have made funds available to you, and ',
       'you have withdrawn the funds, we have the right to reverse the credit for the deposited checks and/or you are still ',
       'responsible for repaying us fo r any checks or other items you deposit or transmit to your account that are returned unpaid ',
       'to us for any reason.  ', ' ',
       'For determining the availability of your deposits, every day is a business day, except Saturdays, Sundays, and federal holida ys.  ',
       'If you make a deposit in person at one of our branch locations before the close of business on a business day that we are open , we will consider that day to be the day of your deposit.  If you deposit a check by Mobile Deposit on a business day ',
       'before the Mobile Deposit service cutoff time, we will consider that day to be the day of your deposit. (For Mobile Deposit Business Day cutoff time information, please refer to the Mobile Deposit information in the applicable Online Banking ',
       'Agreement.)  ', ' ', 'NOTE:  ',
       'Generally, our  close of business is 5:00 p.m. (local time zone), Monday –  Friday, however most of our locations close at 6:00 ',
       'p.m. (local time zone) on Friday.  (Note:  These times may vary by location.)  ', ' ',
       'If you make a deposit into one of our automated teller machines before 3:00 p.m. (local time zone) on a business day we are open, we may consider that day to be the day of deposit.  However, if you make any of the above -mentioned deposits ',
       'after the cut- of time or on a day we are not open, we will consider that the deposit was made on the next business day we ',
       'are open.  ', ' ',
       'Longer Delays May Apply - In some cases, we will not make all of the funds that you deposit by check available to you on ',
       'the first business day after the day of your deposit, including:  ', ' ',
       '• Mobile Deposits - Generally, funds from Mobile Deposits made using our Consumer or BusinessExpress Mobile ',
       'App will be made available the third business day  after the day of deposit; however, the first $225 of your ',
       'Mobile Deposits will be available on the  first business day  after the day of deposit. In certain circumstances ',
       'longer delays may apply, such as when your Mobile Deposits total more than $5,525  on any one day, in which ',
       'case the amount over $5,525  will generally be available no later than the sevent h business day  after the day ',
       'of deposit.  ', ' ',
       '• Other Check Deposits (on a case -by-case basis) - On a case -by-case basis funds from certain checks that you ',
       'deposit may not be available until the second business day  after the day of your deposit; however, the first ',
       '$225  of your deposit will be available on the first business day  after the date of deposit.  ', ' ',
       'If we are not going to make all of the funds from your deposit available on the first business day , we will notify you at the ',
       'time you make your deposit. We will also tell you when the funds will be available. If your deposit is not made directly to ',
       'one of our employees, or if we decide to take this action after you have left the premises, we will send  you a notice by the ',
       'day after we receive your deposit.  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       '                                                                                                  Global Checking – Deposit Agreement  Addendum 10-02-2023 I Page 1 of 2 ',
       ' ', ' ', '     ', ' Global  Checking    ', 'DEPOSIT AGREEMENT ADDENDUM  ', 'Effective January 26, 2023 ', ' ',
       '   ', '(Continued)  ', ' ',
       'If you will need the funds from a deposit right away, you should ask us when the funds will be available.  ',
       ' ',
       'In addition, funds you deposit by check (including Mobile Deposits) may be delayed for a longer period under the following ',
       'circumstances:  ', ' ', '\uf0a7 We believe a check you deposit will not be paid.  ',
       '\uf0a7 You deposit checks totaling more than $5,525  on any one day.  ',
       '\uf0a7 You redeposit a check that has been returned unpaid.  ',
       '\uf0a7 You have overdrawn your account repeatedly in the last six months.  ',
       '\uf0a7 There is an emergency, such as failure of communications or computer equipment.  ', ' ',
       'We will notify you if we delay your ability to withdraw funds for any of these reasons, and we will tell you when the funds w ill ',
       'be available.  They will generally be available no later than the seventh business day after the day of your deposit.  ',
       ' ', '         Effective January 26, 2023  ', ' ',
       'Special Rules for New Accounts  – If you are a new customer, the following special rules will apply during the  first 30 days your ',
       'account is open.  ', ' ',
       'Funds from electronic direct deposits to your account will be available on the day we receive the deposit. Funds from deposit s ',
       'of cash, wire transfers and the first $5,525  of a day’s total deposits of cashier’s, certified, teller’s, traveler’s and federal, state ',
       'and local government checks, will be available on the  first business day  after the day of your deposit if the deposit meets ',
       'certain conditions. For example, the checks must be payable to you. The excess over $5,525  will be available on the ninth ',
       'business day  after the day of your deposit. If your deposit of these checks (other than a U.S. Treasury check) is not made in ',
       'person to one of our employees, the first $5,525  will not be available until the second business day  after the day of your ',
       'deposit.  ', ' ',
       'Funds from all other check deposits will be available on the ninth business day  after the day of your deposit.  ',
       ' ', 'NOTE:  ',
       'The foregoing rules do not apply to deposits of foreign items (items drawn on or payable through or at an office of a ',
       'depository institution not located in the U.S.).  ', ' ', '2. New Account Funds Usage Limitations  ',
       'Updated October 2, 2023  ', ' ',
       'New accounts that are opened  through our Online Banking service may be subject to certain access and usage limitations  until the ',
       'Bank’s new account fraud risk assessment has been completed. This fraud risk assessment hold may result in your initial fundi ng ',
       'deposit not being readily available for uses that may otherwise be generally permitted under the terms of the Bank’s Deposit ',
       'Account Agreement  or other agreements governing your account and services. Please refer to the Annual Percentage Yield and ',
       'Account Terms Disclosure  received a t account opening for additional details.  ', ' ',
       '3. State Law Applicability  for Digitally Acquired Consumer Customers  ', ' ', 'Effective January 26, 2023  ',
       ' ',
       'Accounts opened by consumers that become a Bank customer using the East We st Bank  Mobile App or Online Banking service  will ',
       'be established at a California location and be subject to Califor nia state spe cific laws, unless they used or entered an “invite link”  ',
       'provided by an East West Bank branch located in another state, in which case their account(s) will be established at that branch ',
       'location and subject, where applicable, to that state’s specific laws as defined in the Bank’s Deposit Agreement .   ',
       ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', '  ', ' ',
       '                                                                                                          ',
       '                                                                                                                         Global Checking –  Deposit Agreement Addendum 10 -02-2023 I Page 2 of 2']
lst2 = ['                                                                ', ' ', '                             ', ' ',
        ' ', '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ', ' ',
        '      East West Bank   ', '     Global  Checking   ', ' ',
        '       Interest Rates                                                  ', ' ', '  ', '                    ',
        '                           Daily Balance       ', 'Interest Rate         ', 'Annual Percentage Yield  ', ' ',
        '$0.00   ', ' to  ', '$9,999.99             0.025% 0.03% ', ' ', '$10,000.00  ', ' to  ',
        '$24,999.99             0.025% 0.03% ', ' ', '$25,000.00  ', 'to  ', '$49,999.99             0.025% 0.03% ',
        ' ', '$50,000.00  ', 'to  ', '$99,999.99             0.025% 0.03% ', ' ', '$100,000.00   ', 'to  ',
        '$249,999.99             0.045% 0.05% ', ' ', '$250,000.00  ', 'to  ', '$499,999.99             0.045% 0.05% ',
        ' ', '$500,000.00  ', 'to  ', '$999,999.99             0.045% 0.05% ', ' ', '$1,000,000.00   ', 'to  ',
        '           and above             0.045% 0.05% ', ' ', ' ', '  Variable Rate Account   ',
        'Your interest rate is variable and may be changed  at any time, at our discretion and without ',
        'prior notice.  ', ' ', ' ', 'Interest Accrual /  ', 'Payment Frequency   ',
        'Interest begins to accrue on the day you make your deposit, and is credited to your account ',
        'on a monthly basis.  ', ' ', ' ', 'Interest Compounding / ', 'Computation   ',
        'Your interest is compounded daily on an actual/365 day basis.  We use the daily balance method, which applies a daily periodic rate to the principal in the account each day.  ',
        ' ', '         ', '       Terms and Conditions  ', ' ', ' ', 'Minimum Opening Balance   ', '$25,000  ', ' ',
        'Account must be funded within 60 days of  application approval with a  minimum opening ',
        'deposit of $25,000  or more .  Funding deposits received for an amount that is less than $25,000 ',
        'are, at the discretion of the Bank, subject to return . Accounts that are not funded within 60 ',
        'days  will be subject to automatic closure.  ', ' ',
        'Additionally, the Bank reserves  the right to automatically close  an account that at any time has ',
        'had a continuous $0 balance for 60 days,  that is overdrawn or otherwise not maintained in ',
        'good standing, or  for any reason in accordance with the terms of the Bank’s Deposit ',
        'Agreement .  Generally, accounts with an unresolved  overdraft condition will be closed within   ',
        '45 days  of the overdraft date, but  timing of the closure is solely at the discretion of the Bank. ',
        'For additional information please refer to Bank’s Deposit Agreement.  ', ' ',
        'Requests  to re -open an account  that h as been closed  by the Bank or customer are  subject to ',
        'Bank review and approval . If, at the Bank’s discretion, an account re -opening request is ',
        'honored , the minimum opening balance requirement will apply . The Bank is under no ',
        'obligation to honor a re -opening request, and not all accounts will qualify for re -opening.  Please ',
        'refer to the Bank’s  Deposit Agreement , provided at the time of account opening, for additional ',
        'information .  ', ' ', ' ', ' ', 'Account Opening Fee   ', '$300   ', ' ',
        'A one-time Account Opening Fee will be automatically deducted  from the account upon ',
        'receipt of a minimum opening deposit of $ 25,000 or more.   ', ' ',
        '\uf0a7 Depending on your initial funding amount, the  deduction of the Account Opening Fee ',
        'may result in your account balance falling below the minimum average balance required ',
        'to avoid a monthly account maintenance fee.   ', ' ',
        '(See “Account Opening Fee Refund  Qualification Requirements ” and “Minimum Average Balance Required ',
        'to Avoid the Monthly Maintenance Fee” section s for additional information.)  ', ' ', '\uf0a7  ', '  ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        '                                                                                                                                                                                                                                                                                                                     Global Checkin g 4-13-2024 I Page 1 of 4  ',
        ' ', '                                                                 ', '        ',
        '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ',
        '                                                                                                              Cont.       ',
        ' ', 'Monthly Maintenance Fee   ', '$25 ', ' ',
        'Charged per monthly statement cycle if the minimum average monthly balance maintained in ',
        'the account during the statement cycle does not meet the required minimum.  ', ' ',
        '\uf0a7 Please note, your Monthly Maintenance Fee assessment will be waived for the first two ',
        'monthly statement cycles after account opening.  For example, if you open your account ',
        'in January, your first Monthly Maintance Fee assessment will be for the month of Ma rch.    ', '   ',
        'Minimum Average Balance ', 'Required to Avoid the Monthly ',
        'Maintenance Fee      Your Monthly Maintenance Fee will be waived if you maintain a:  ', ' ',
        '1. $25,000 average balance in your account each monthly statement cycle  ',
        '                                         OR ',
        '2. $50,000  prior month -end combined average balance  in the qualifying consumer ',
        'deposit accounts you own at East West Bank  ', ' ', 'Account Opening Fee Refund  ',
        'Qualification R equirements   ',
        'During the first 12 months  (full or partial)  after the initial funding requirement is met, you will ',
        'have an opportunity to qualify for up to $300  in Account Opening Fee refunds .  ', ' ',
        '\uf0a7 For each month  during the qualification period where you have maintained a combined ',
        'month -end average balance of $100,000 or more  in the qualifying consumer deposit ',
        'accounts you own at East West Bank, you’ll receive a $100  Account Opening Fee refund . ', ' ',
        '\uf0a7 Upon qualification, your  $100 Account Opening Fee refund will be automatically  ',
        'credited to your Global Checking account  within 10 business days . ', ' ',
        'o Maximum refund amount:  $300, earned over 3 qualifying months  ', ' ',
        'Additionally, a t the sole discretion of the Bank, the initial Account Opening Fee may be ',
        'refunded  if, due to the Bank’s post -funding fraud risk assessment s, the account is closed by ',
        'the Bank within the first 30 calendar days after payment of the Account Opening Fee.  As ',
        'applicable , the Account Opening Fee refund amount will be credited to the account at the time ',
        'of closure.   ',
        '                                                                                                                                                                                ',
        'Additional Terms and Conditions                                                                                             ',
        '   ', ' ', 'Qualification Requirements   ',
        'Limited to individuals 18 years of age or older.  One account per customer.  ', ' ', ' ',
        'Subject to Bank Approval   ',
        'Account applications are subject to verification and approval. Submission of an application ',
        'does not guarantee that East West Bank will open an account for you.   ', ' ',
        'Additionally, we may conduct fraud risk assessments both at the time of application, and upon ',
        'receipt of your initial funding deposit, which may result in your initial funding deposit being ',
        'subject to certain access and usage limitations  until the fraud risk assessments are completed. ',
        'If you have questions regarding your initial funding deposit after account opening, you can contact us at (CN) +',
        '86.400. 080.5290  or (U.S.) + 1.833.468.8356.     ', ' ',
        'East West Bank reserves the right to close an account and return the initial funding deposit to the sender, without prior notice, based on the results of our risk assessment findings.   ',
        ' ', ' ', 'Account Title and  ', 'Contact Information   ',
        'By submitting an application you are requesting to open a Global  Checking account at East ',
        'West Bank, a United States financial institution.  If approved, a Global Checking  account will ',
        'be opened in your name, as sole owner.  Your contact e- mail address, mobile phone number, ',
        'primary residence address and alternate account mailing address will be defined based on the ',
        'information you agreed to share with us.  If an alternate ac count mailing address was not ',
        'provided, we will use your residence address as the mailing address for your account.  ', '          ',
        'Check Orders   ',
        'Your East West Bank account will NOT have checks automatically issued. If you would like to ',
        'order checks you may contact us at (CN) + 86.400. 080.5290 or (U.S.) + 1.833.468.8356.  ', ' ', ' ',
        'Check Imaging   ',
        'Check Imaging is a process of capturing, indexing, storing and retrieving electronic images of ',
        'checks.  Imaging systems replace the handling, distribution and storage of checks with ',
        'electronic images.  The images are retained by us for a period of seven years from the date of ', 'posting.  ',
        ' ',
        'By using your account you agree to this procedure and authorize us to destroy the original items and check.  You agree to allow any imaged document, or copy thereof, to serve as an ',
        'original item for any and all purposes, including charging your account or determining the ',
        'validity of any signatures or otherwise.  ', ' ', ' ', ' ',
        '                                                                                                                                                                                                                                                                                                                       Global Checking 4-13-2024 I Page 2 of 4                                                                  ',
        '         ', '                           ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ',
        '                                                                                                              Cont.  ',
        '  ', ' ', 'Debit Card Issuance /  ', 'ATM Access  ', '  ',
        'A Debit Card will NOT be automatically issued.  If you would like to request a Debit Card you ',
        'may request a card in our M obile App or Online Banking service s, or contact us at (CN) ',
        '+86.400. 080.5290 or (U.S.) + 1.833.468.8356.  ', ' ',
        'If requested, your Debit Card will be issued in your name and mailed to the address associated ',
        'with your Global  Checking  account. For shipments to China, your Debit Card will be mailed to ',
        'the one- time shipping address you provided and verified at the time of request.  For cards ',
        'delivered to an international address, a shipping fee will apply.  Please refer to the East West ',
        'Bank Fee Schedule  for additional details.  ', ' ',
        'Your Global  Checking account will be linked as the primary account that can be accessed using ',
        'the Debit Card.  ', ' ', ' ', 'ATM Withdrawal Fees  ', '  ',
        'There is no charge for using an East West Bank ATM.    ', ' ',
        'Additionally, East West Bank will not charge you a fee when you use a non -East West Bank (3rd ',
        'party) ATM to access funds in your Global Checking  account.   ', ' ',
        'In some cases, the 3rd party operating the non -East West Bank ATM may request us to charge ',
        'a fee to your account.  If this does occur, East West Bank will refund any 3rd party ATM usage ',
        'fees deducted from your Global Checking  account each statement cycle, generally no later ',
        'than the business day following the day the transaction posted to your account.  (Note: This ',
        'waiver does not apply to any East West Bank NSF fees that are the result of your account being ',
        'overdrawn by an AT M transaction.)  ', ' ', ' ', 'Other Fees and Services  ', '  ',
        'Additional fees may apply.  Please refer to the East West Bank Fee Schedule , which has been ',
        'provided with this disclosure, for additional fee information.  ', ' ', 'Velo Gold  ', ' ', ' ',
        'Velo Gold Program  ', '  ',
        'Global Checking customers also have the opportunity to qualify for  our Velo Gold  program, ',
        'which offers enhanced features and benefits.  ', ' ', ' ', 'VELO Gold Benefits  ', '  ',
        'Velo Gold  Benefits include:  ', ' ', '\uf0fc WAIVER of Incoming Wire Fees  ', ' ',
        'We’ll waive East West Bank’s  Incoming Wire fee for your Global Checking account  ', ' ',
        '\uf0fc WAIVER of the International Shipping Fee for Debit Cards  ', ' ',
        'We’ll waive East West Bank’s  International Shipping Fee for Debit Cards  ', ' ',
        'Note:  International Shipping fee is applicable to select countries only  ', ' ',
        '\uf0fc Curated Articles and Resources  ', ' ',
        'Velo Gold  customers will have access to curated articles and resource information in the ',
        '“For You” section of our Mobile App and Online Banking services  ', ' ',
        'Additionally, Velo Gold  customers will have access to these other premium services:  ', ' ',
        '\uf0fc Dedicated Customer Support  ', ' ',
        'You’ll enjoy easy Mobile App and Online Banking access to our dedicated Help Center ',
        'phone line and chat support  ', ' ', '\uf0fc Relationship Manager  ', ' ',
        'A dedicated Relationship Manager, to support all your banking needs  ', ' ', ' ', 'Velo Gold Qualification  ',
        'Requirements  ', '  ', 'To qualify  for the Velo Gold  program , you must be:  ', ' ',
        '1. The primary owner of a Global Checking account; AND  ', ' ',
        '2. Maintain  a combined month -end average balance of $100,000 or more  in the qualifying ',
        'consumer deposit accounts you  own at East West Bank.  ', ' ',
        '\uf0a7 Upon meeting the combined month -end average balance requirement, both you ',
        'and your  Global Checking account  will be  automatically  ENROLLED  in the Velo Gold  ',
        'program  within 10 business days.  ', ' ',
        '                                                                                                                               ',
        ' ', ' ',
        '                                                                                                                                                             ',
        '                                                                                                                                                                                  Global Checking  4-13-2024  I Page 3 of 4                                                                 ',
        '         ', '                          ANNUAL PERCENTAGE YIELD  ', 'AND ACCOUNT TERMS DISCLOSURE      ', ' ',
        '                                                                                                              Cont.  ',
        '  ', ' ', 'Velo Gold Qualification  ', 'Requirements (cont.)  ', ' ', '  ', ' ',
        'If, at any time,  the combined month -end average balances  in the qualifying consumer deposit ',
        'accounts you own at East West Bank fall below $100,000 for four (4) consecutive months , both ',
        'you and your  Global Checking account will be UNENROLLED from the Velo Gold  program  within ',
        '10 business days.  ', ' ',
        '\uf0a7 Customers and accounts that have been unenrolled from the Velo Gold program  will be ',
        'automatically RE -ENROLLED if they again meet  the Velo Gold  program  qualification ', 'requirements.  ', ' ',
        ' ', 'Additional Terms and ', 'Conditions  ', '  ',
        'Qualifying consumer deposit accounts for Maintenance Fee Waiver and Velo Gold program  ',
        'qualification purposes are determined by East West Bank. The balance from a qualifying ',
        'account will be allocated to a single account owner’s combined balance calculation only, and ',
        'the account owner   that will receive the allocation will be determined solely by East West Bank.  ',
        'Wealth Management accounts, Commercial accounts and other non -USD deposit account ',
        'products do not qualify.  ', ' ',
        'Customers that are currently enrolled in the  Velo Gold  program  generally will not qualify for ',
        'new enrollment in the Bank’s exclusiveBridgePlus or eliteBridgePlus programs.  ', ' ',
        'The Velo Gold  program benefits  are not exchangeable for other services, are  non-transferable ',
        'and have no cash  or rebate value.  Velo Gold  program  terms and benefits are subject  to change ',
        'or termination at the discretion of East West bank without notice.  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        '                                                                                                                                                             ',
        '                                                                                                                                                                                Global Checking  4-13-2024  I Page 4 of 4                                                              ',
        ' ', ' ', '                             ', ' ', '  ', ' ', ' ', 'Global  Checking  ',
        'DEPOSIT AGREEMENT ADDENDUM  ', 'Effective January 26, 202 3 ', ' ',
        'This Deposit Agreement Addendum  amends and supersedes, where applicable, the Bank’s Deposit Agreement  ',
        'dated 6/18/2015 and applies specifically to accounts opened using the East W est Bank  Mobile App or Online ',
        'Banking services.  ', ' ', '   ', '  ', '1. Holds for Uncollected Funds / Delayed Funds Availability  ',
        'Updated October 2 , 2023     ',
        '      The below revised information amends the “Ability to Withdrawal Funds”, “Longer Delays May Apply” and “Special Rules for ',
        'New Accounts”  information contained in the Holds for Uncollected Funds / Delayed Funds Availability  section of the Bank’s ',
        'Deposit Agreement . All other information contained in the Holds for Uncollected Funds / Delayed Funds Availability  section ',
        'of the Deposit Agreement  remains the same.  ', ' ',
        'Ability to Withdrawal Funds - Generally, our policy is to make funds from your deposits available to you on the first business ',
        'day after the day we receive your deposit, although specific account types, check types or deposit methods may be subject ',
        'to delayed funds availability. Electronic direct deposits will be available on the day we receive the deposit. Once they are ',
        'available, y ou can withdraw the funds in cash and we will use the funds to pay checks that you have written.  ',
        ' ',
        'In many cases we will make the funds from your deposited checks available to you sooner than we are able to collect the funds from the paying bank, and it is possible for a check or other item to be returned to us as unpaid days, weeks or months  ',
        'after we h ave made the funds available to you. Please remember that even after we have made funds available to you, and ',
        'you have withdrawn the funds, we have the right to reverse the credit for the deposited checks and/or you are still ',
        'responsible for repaying us fo r any checks or other items you deposit or transmit to your account that are returned unpaid ',
        'to us for any reason.  ', ' ',
        'For determining the availability of your deposits, every day is a business day, except Saturdays, Sundays, and federal holida ys.  ',
        'If you make a deposit in person at one of our branch locations before the close of business on a business day that we are open , we will consider that day to be the day of your deposit.  If you deposit a check by Mobile Deposit on a business day ',
        'before the Mobile Deposit service cutoff time, we will consider that day to be the day of your deposit. (For Mobile Deposit Business Day cutoff time information, please refer to the Mobile Deposit information in the applicable Online Banking ',
        'Agreement.)  ', ' ', 'NOTE:  ',
        'Generally, our  close of business is 5:00 p.m. (local time zone), Monday –  Friday, however most of our locations close at 6:00 ',
        'p.m. (local time zone) on Friday.  (Note:  These times may vary by location.)  ', ' ',
        'If you make a deposit into one of our automated teller machines before 3:00 p.m. (local time zone) on a business day we are open, we may consider that day to be the day of deposit.  However, if you make any of the above -mentioned deposits ',
        'after the cut- of time or on a day we are not open, we will consider that the deposit was made on the next business day we ',
        'are open.  ', ' ',
        'Longer Delays May Apply - In some cases, we will not make all of the funds that you deposit by check available to you on ',
        'the first business day after the day of your deposit, including:  ', ' ',
        '• Mobile Deposits - Generally, funds from Mobile Deposits made using our Consumer or BusinessExpress Mobile ',
        'App will be made available the third business day  after the day of deposit; however, the first $225 of your ',
        'Mobile Deposits will be available on the  first business day  after the day of deposit. In certain circumstances ',
        'longer delays may apply, such as when your Mobile Deposits total more than $5,525  on any one day, in which ',
        'case the amount over $5,525  will generally be available no later than the sevent h business day  after the day ',
        'of deposit.  ', ' ',
        '• Other Check Deposits (on a case -by-case basis) - On a case -by-case basis funds from certain checks that you ',
        'deposit may not be available until the second business day  after the day of your deposit; however, the first ',
        '$225  of your deposit will be available on the first business day  after the date of deposit.  ', ' ',
        'If we are not going to make all of the funds from your deposit available on the first business day , we will notify you at the ',
        'time you make your deposit. We will also tell you when the funds will be available. If your deposit is not made directly to ',
        'one of our employees, or if we decide to take this action after you have left the premises, we will send  you a notice by the ',
        'day after we receive your deposit.  ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        '                                                                                                  Global Checking – Deposit Agreement  Addendum 10-02-2023 I Page 1 of 2 ',
        ' ', ' ', '     ', ' Global  Checking    ', 'DEPOSIT AGREEMENT ADDENDUM  ', 'Effective January 26, 2023 ', ' ',
        '   ', '(Continued)  ', ' ',
        'If you will need the funds from a deposit right away, you should ask us when the funds will be available.  ',
        ' ',
        'In addition, funds you deposit by check (including Mobile Deposits) may be delayed for a longer period under the following ',
        'circumstances:  ', ' ', '\uf0a7 We believe a check you deposit will not be paid.  ',
        '\uf0a7 You deposit checks totaling more than $5,525  on any one day.  ',
        '\uf0a7 You redeposit a check that has been returned unpaid.  ',
        '\uf0a7 You have overdrawn your account repeatedly in the last six months.  ',
        '\uf0a7 There is an emergency, such as failure of communications or computer equipment.  ', ' ',
        'We will notify you if we delay your ability to withdraw funds for any of these reasons, and we will tell you when the funds w ill ',
        'be available.  They will generally be available no later than the seventh business day after the day of your deposit.  ',
        ' ', '         Effective January 26, 2023  ', ' ',
        'Special Rules for New Accounts  – If you are a new customer, the following special rules will apply during the  first 30 days your ',
        'account is open.  ', ' ',
        'Funds from electronic direct deposits to your account will be available on the day we receive the deposit. Funds from deposit s ',
        'of cash, wire transfers and the first $5,525  of a day’s total deposits of cashier’s, certified, teller’s, traveler’s and federal, state ',
        'and local government checks, will be available on the  first business day  after the day of your deposit if the deposit meets ',
        'certain conditions. For example, the checks must be payable to you. The excess over $5,525  will be available on the ninth ',
        'business day  after the day of your deposit. If your deposit of these checks (other than a U.S. Treasury check) is not made in ',
        'person to one of our employees, the first $5,525  will not be available until the second business day  after the day of your ',
        'deposit.  ', ' ',
        'Funds from all other check deposits will be available on the ninth business day  after the day of your deposit.  ',
        ' ', 'NOTE:  ',
        'The foregoing rules do not apply to deposits of foreign items (items drawn on or payable through or at an office of a ',
        'depository institution not located in the U.S.).  ', ' ', '2. New Account Funds Usage Limitations  ',
        'Updated October 2, 2023  ', ' ',
        'New accounts that are opened  through our Online Banking service may be subject to certain access and usage limitations  until the ',
        'Bank’s new account fraud risk assessment has been completed. This fraud risk assessment hold may result in your initial fundi ng ',
        'deposit not being readily available for uses that may otherwise be generally permitted under the terms of the Bank’s Deposit ',
        'Account Agreement  or other agreements governing your account and services. Please refer to the Annual Percentage Yield and ',
        'Account Terms Disclosure  received a t account opening for additional details.  ', ' ',
        '3. State Law Applicability  for Digitally Acquired Consumer Customers  ', ' ', 'Effective January 26, 2023  ',
        ' ',
        'Accounts opened by consumers that become a Bank customer using the East We st Bank  Mobile App or Online Banking service  will ',
        'be established at a California location and be subject to Califor nia state spe cific laws, unless they used or entered an “invite link”  ',
        'provided by an East West Bank branch located in another state, in which case their account(s) will be established at that branch ',
        'location and subject, where applicable, to that state’s specific laws as defined in the Bank’s Deposit Agreement .   ',
        ' ', ' ', ' ', ' ', '  ', ' ', ' ', ' ', '  ', ' ',
        '                                                                                                          ',
        '                                                                                                                         Global Checking –  Deposit Agreement Addendum 10 -02-2023 I Page 2 of 2']
